# line.yaml

out_dir: results
metric_best: acc
cfg_dest: gae.yaml
print: file
seed: 0
accelerator: auto

run:
  seed: 0
  num_threads: 11
  multiple_splits: None


wandb:
  use: True
  project: gtblueprint
  name_tag: gae-arxiv_2023-origin

train:
  mode: custom
  batch_size: 2048
  eval_period: 1
  epochs: 1000
  device: 0
  auto_resume: False
  final_eval: False
  finetune: False

model:
  type: GAE
  out_channels: 32
  in_channels: None
  hidden_channels: 32

num_threads: 11

data:
  name: arxiv_2023
  undirected: True
  include_negatives: True
  val_pct: 0.125
  test_pct: 0.025
  split_labels: True
  num_features:  128
  device: 0
  split_index: [0.4, 0.125, 0.025] #[0.8, 0.15, 0.05]

optimizer:
  type: adam
  base_lr: 0.001
  weight_decay: 0.0005