# line.yaml

out_dir: results
metric_best: acc
cfg_dest: gat.yaml
print: file

run:
  seed: 0
  num_threads: 11
  multiple_splits: None


wandb:
  use: True
  project: gtblueprint
  name_tag: gat-arxiv_2023-origin


num_threads: 11

train:
  mode: custom
  batch_size: 2048
  eval_period: 1
  epochs: 2000
  device: 1
  auto_resume: False
  final_eval: False
  finetune: False


model:
  type: GAT
  in_channels: 12
  out_channels: 128
  heads: 1
  hidden_channels: 8  
  negative_slope: 0.2
  dropout: 0
  num_layers: 2

num_threads: 11

data:
  name: arxiv_2023
  undirected: True
  include_negatives: True
  val_pct: 0.15
  test_pct: 0.05
  split_labels: True
  num_features:  128
  split_index: [0.4, 0.125, 0.025]


