# line.yaml

out_dir: results
metric_best: acc
cfg_dest: gsaint.yaml
print: file
seed: 0

run:
  seed: 0
  num_threads: 11
  multiple_splits: None

wandb:
  use: True
  project: gtblueprint
  name_tag: gsaint-arxiv_2023-origin
  
train:
  mode: custom
  batch_size: 2048
  eval_period: 1
  epochs: 10 #10000
  device: 1
  use_valedges_as_input: True
  lr: 0.01 # {0.1, 0.01, 0.001, 0.0001}
  l2: 0.0
  auto_resume: False
  finetune: False

  
model:
  type: GAE # Here you can paste different name of model
  sampler: None #gsaint
  out_channels: 32
  heads: 4
  hidden_channels: 32  # {128, 256, 512}
  in_channels: 128
  batch_size_sampler: 256
  walk_length: 50
  num_steps: 20
  sample_coverage: 100

num_threads: 11

data:
  name: arxiv_2023
  undirected: True
  include_negatives: True
  val_pct: 0.125
  test_pct: 0.025
  split_labels: True
  num_features: 128
  device: 1
  split_index: [0.4, 0.125, 0.025]

optimizer:
  type: adam
  base_lr: 0.01
  weight_decay: 0.0005
