# line.yaml

out_dir: results
metric_best: acc
cfg_dest: vgae.yaml
print: file
seed: 0
run_multiple_splits: None

wandb:
  use: True
  project: gtblueprint
  name_tag: vgae-arxiv_2023-origin

train:
  mode: custom
  batch_size: 32   
  eval_period: 1
  epochs: 2000
  auto_resume: False
  lr: 0.01
  
model:
  type: vgae
  out_channels: 16
  hidden_channels: 8  # Assume that the dimension of the hidden layer feature is 8
  in_channels: 128 # Missed! AttrubuteError
    
num_threads: 11

data:
  name: arxiv_2023
  undirected: True
  include_negatives: True
  val_pct: 0.125
  test_pct: 0.025
  split_labels: True
  num_features: 128
  split_index: [0.4, 0.125, 0.025]
